# -*- coding: utf-8 -*-#

# ---------------------------------------------
# Name:         text
# Description:  
# Author:       Laity
# Date:         2021/10/22
# ---------------------------------------------
kite_origin = '''
The kite festival originated in the Tang Dynasty of China. Many cities in China still have kite festivals, and almost all other Southeast Asian countries have kite festivals. But perhaps after thousands of years of changes, the kite festivals in these countries are no longer in the same season. If the kite festivals in these countries add up, the duration of the festival lasts almost all the year round.

Kites are called "Zhiyuan" in North China and "Kite" in South China. The name "Kite" began in the Five Dynasties (907-960 AD). According to the records of inquiring about Hungary by Lang Ying of the Ming Dynasty, there was a man named Li Ye in the Five Dynasties who made a paper kite in the palace, led a line to ride the wind for play, tied a bamboo whistle on the head of the paper kite, and when flying, the wind entered the bamboo whistle and made a sound like "Zheng", so it was called "Kite".

How was the kite invented? Some people say that our ancestors were inspired by the wind blowing hats and leaves, some by sails or tents, and others by birds. There are different opinions. However, the earliest kite appeared in China, which is a consensus in the international kite industry. When the famous ancient Chinese philosopher Mo Zhai (468-376 BC) lived in Lushan (now the southwest of Qingzhou, Weifang, Shandong Province), he once "made a wooden kite in three years and lost in one day". This is the earliest kite in the world. It has a history of more than 2300 years. Later, Mo Zhai passed the method of making wooden harriers to his students' public transport class (also known as Luban and Luban). The public transport class improved and made "bamboo magpies" with bamboo as materials, which can fly in the air for three days. The Gongshu class also "made wooden kites to see the song city" and used kites for military purposes. Early kites were also used to send distant messages and measure wind power. According to the records of duyizhi, in the third year of the Taiqing Dynasty (A.D. 549), Emperor Liang Wu was trapped in Taicheng near Nanjing by rebel Hou Jing. Jian Nu offered a plan as a paper kite to hide the imperial edict in China and fly a letter in the air to seek reinforcements. Because the kite was shot down by the enemy, it failed.

As an entertainment tool, kite began in the Tang Dynasty. In 713 ad, Li Longji, Emperor Xuanzong of the Tang Dynasty, watched the flying of the kite "Eight Immortals crossing the sea" in Yichun courtyard of Penglai palace, Shandong Province. There are many records of emperors and nobles enjoying kites in the < < Xuanhe kite manual > > of the Song Dynasty. Due to the emergence of papermaking, kites changed to paper paste, which greatly reduced the cost and soon spread to the people. Since then, with international exchanges, kites have spread all over the world. In the history of Chinese science and technology, Joseph Needham, a famous British scholar, listed the kite as one of the major scientific inventions spread by the Chinese nation to Europe. Just as a foreign kite expert said, "it is universally acknowledged that the Chinese people invented kites 2000 years ago. Kites aroused the reverie of human beings flying to the sky and led to the invention of the world's first real aircraft." the progress of the times has changed the role of kites. In history, the use of kites has been changed many times. Its initial function is said to be used for military. Many historical materials have mentioned that Han General Han Xin once flew kites into the air and calculated the distance to Weiyang palace according to the length of the kite flying line. It has been recorded in history books that in 559 ad, Emperor Wen Xuan of Qi ordered prisoners to fly down from a gold wind platform eight feet high (about 26 meters high, today's disabled platform is 12 meters high) by kite. Those who can fly out of the city can be pardoned for their death. The prisoners were anxious to survive and "each took a paper to fly". As a result, a death row prisoner named Huang tou successfully glided by kite and floated safely to a place called Zimo outside the city, but later he was arrested and starved to death in prison.

Before the Tang Dynasty, most kites were relatively large and could carry people. Whether they were successful or not is another matter. We can only speculate that the flying technology has been mature It is also recorded in the biography of Tian Yue in the new book of the Tang Dynasty that in the second year of Jianzhong of the Tang Dynasty (AD 781), Zhang Pi was trapped in a critical situation by the rebel Tian Yue's army. Zhang Pi was "anxious to take paper as the wind kite". There was a saying in the book "don't understand for three days, face famous people and eat for joy". After the wind kite took off, "it is hundreds of feet high and goes over the Yue camp". Tian Yue ordered those who are good at shooting, but it can't reach it, The request for help was finally delivered to the reinforcements by the kite, so the siege was relieved. By the middle of the Tang Dynasty, it had entered a prosperous and stable development stage. The function of kites began to shift from military use to entertainment. At the same time, due to the development of the paper industry, the kite making materials began to use paper from silk. Kites have become popular, and there are more types of kites. Yuan Zhen, a poet of the middle Tang Dynasty (779-831 AD), wrote in his object chanting poem "there are birds and twenty chapters of paper kites", that "there are birds and paper kites, which are led by children due to the false trend of the wind" (see the kite poetry column for the full text). Other poets have also written kite chanting poems many times in Tang poetry. Through these documents, we can see the kite activities in the prosperous Tang Dynasty.

In the Song Dynasty, kites spread more widely. Huizong of the Song Dynasty was an enthusiastic advocate of kites. In addition to flying kites in the palace himself, he is said to have presided over the compilation of a book, "Xuanhe kite manual". With the participation of scholars, pictographic kites had a great development in binding and decoration. At that time, kites had become common toys for children. Children competed to fly the wind Zheng has become a scene in the suburbs in spring. At the same time, due to the social demand for kites, making kites has become a special profession. In addition, there has been a professional person who specializes in flying kites "taking advantage of people". At that time, many painters were also willing to take the theme of flying kites into their paintings. The paintings of Guo Zhongshu, a famous painter and writer in the Song Dynasty, are very popular.

In the Ming and Qing Dynasties, the development of kites reached its peak. Because the age is not too far away, there are many documents and materials about kites. Kites in the Ming and Qing dynasties have made great progress in size, style, binding technology and decorative flying skills. Kites in the Ming and Qing Dynasties are also richer in decorative techniques than in the past. Kites and various folk crafts began to change At that time, New Year picture workshops also used woodblock New Year pictures to print kite paper, and the decorative techniques and materials used by civilian paper binding artists were also diversified: stickers, paper-based plastic reliefs, paper-cut, gold and silver painting, paper flowers, etc. there was also development in the sound device. In addition to the sound bow in the past, "bamboo and reed were used to attach the spring to the back of the kite, which was called" kite whip "because of the atmosphere." In the coastal area, whistles are made of gourds and white fruit shells. They are mounted on kites in different numbers and sizes. Their pronunciation is powerful and can be heard from several miles around. In the Ming and Qing Dynasties, many writers and painters also recited poems and paintings on kites, leaving many excellent works. Xu Wei, a painter in the Ming Dynasty (1521-1593 A.D.) In his later years, he painted many kite paintings and wrote many kite painting poems. According to the statistics of later generations, there are more than 30. In Yangjiabu and Yangliu youth paintings, there are also kite flying as the theme. At that time, many scholars also painted kites by themselves. In addition to flying by themselves, they also gave friends as gifts, and thought it was a very elegant thing. Among them, Cao Xueqin, a literary scientist and author of a dream of Red Mansions, was the most representative. He gave a very detailed introduction to kites in his work "the record of the test of kites in the South and kites in the north". It is said that 43 kite binding techniques were introduced in this book.

In modern times, especially in the past 20 years, China's kite industry has made great progress. Kite has become popular as a sports event and fitness, leisure and entertainment activities. Kite competitions at home and abroad have promoted the popularity of kite. More and more people begin to join this activity.
'''